### ISSUE TITLE
Implement trajectory following in Simulator

### ISSUE THREAD

**Issue by DaniilOkladnikov** [Racetech-DV/Racetech-DV_BFMC2024#19]

**Comment by pi-tronic** [comment]
https://www.mathworks.com/help/nav/ug/pure-pursuit-controller.html

**Comment by pi-tronic** [comment]
![track with nodes](https://github.com/Racetech-DV/Racetech-DV_BFMC2024/assets/118998605/7c186649-8eab-4e73-b0c9-beb4558bbe33)

**Comment by pi-tronic** [comment]
- stole a pure pursuit code, worked, but classes...
- able to read nodes from file and display them with matplotlib, to later put pure pursuit on them

![read track](https://github.com/Racetech-DV/Racetech-DV_BFMC2024/blob/19-implement-trajectory-following-in-simulator/Figure_3.png?raw=true)

**Comment by pi-tronic** [comment]
Added the ppc into the map, just for fun.

Not ideal, as it is driving onto the wrong lane, but could be used if time demands it..

![track with trajectory](https://github.com/Racetech-DV/Racetech-DV_BFMC2024/blob/19-implement-trajectory-following-in-simulator/Figure_4.png?raw=True)

**Comment by pi-tronic** [comment]
[Schnittpunkte am Kreis finden...](https://mathworld.wolfram.com/Circle-LineIntersection.html)

Hell yeah! Ansatz Nummer #423454346............!!"E!"$RFEF§

Currently working on selfmade PPC to gain more control over behavior. Maybe 35% done (+- 20% >:()

**Comment by pi-tronic** [comment]
new approach: there is a back-port of the nav2 pure pursuit controller

test this on simulator till 14.01.24

[link to back-port](https://github.com/JohnTGZ/regulated_pure_pursuit_controller)

**Comment by pi-tronic** [comment]
back-port of nav2 is not suited

found some promising PPCs which require the odometry topic -- therefore an odometry plugin is necessary

- [x] install odometry plugin
