### ISSUE TITLE
Extract depth map from 3D Cam

### ISSUE THREAD

**Issue by DaniilOkladnikov** [Racetech-DV/Racetech-DV_BFMC2024#9]
1) Where is the camera? Ask Adrian
2) What should we do exactly? You should connect to your ubuntu laptop and see how to get point clouds and RGB images with this camera

**Comment by Bigfire3** [comment]
Cam ist bei mir. RGB Bild bekommen wir easy, Punktwolke geht auch, müssen wir aber nochmal drüber reden. Würde gerne mit euch auch über die Objekterkennung sprechen.

**Comment by Bigfire3** [comment]
Mapping einzeln erkannter Punkte erscheint mir ressourcensparender

**Comment by DaniilOkladnikov** [comment]
> Cam ist bei mir. RGB Bild bekommen wir easy, Punktwolke geht auch, müssen wir aber nochmal drüber reden. Würde gerne mit euch auch über die Objekterkennung sprechen.

Was ist da mit Punktwolken?
